---
HOSTS:
  centos-server-el7:
    platform: el-7-x86_64
    hypervisor: vagrant
    roles:
    - agent
    - master
    - default
    - server
    ip: 192.168.103.7
    netmask: 255.255.255.0
    mac: aabbcccc0007
CONFIG:
  nfs_server: none
  consoleport: 443
  box: centos/7
  log_level: debug
  type:      aio
  vagrant_memsize: 4096
  #vb_gui: false
